export type DoneStateEnv = Env & Readonly<{
  CANONICAL_ORIGIN?: string;
  COOKIE_ENCRYPTION_KEY: string;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  TOKEN_ENCRYPTION_KEY: string;
  USER_CREDENTIAL_ENCRYPTION_KEY: string;
  OPENAI_APPS_CHALLENGE?: string;
  OPENAI_REVIEW_PASSWORD_SHA256?: string;
  OPSTRUTH_MCP_URL?: string;
  OPSTRUTH_VERIFIER_FINGERPRINT?: string;
  PLATFORM_OWNER_LOGIN?: string;
}>;
