export type DoneStateEnv = Omit<Env, "DEPLOYMENT_MODE"> & Readonly<{
  CANONICAL_ORIGIN?: string;
  DEPLOYMENT_MODE?: "production" | "marketplace-development";
  COOKIE_ENCRYPTION_KEY: string;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  GITHUB_MARKETPLACE_WEBHOOK_SECRET?: string;
  TOKEN_ENCRYPTION_KEY: string;
  USER_CREDENTIAL_ENCRYPTION_KEY: string;
  OPENAI_APPS_CHALLENGE?: string;
  OPENAI_REVIEW_PASSWORD_SHA256?: string;
  OPSTRUTH_MCP_URL?: string;
  OPSTRUTH_VERIFIER_FINGERPRINT?: string;
  OPSTRUTH_REVOKED_VERIFIER_FINGERPRINTS?: string;
  PLATFORM_OWNER_LOGIN?: string;
}>;
